osx_image: xcode8.3

dist: trusty
sudo: required

services:
  - docker

language: node_js
node_js: "6"

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  
cache:
  directories:
   - $HOME/.yarn-cache
  
before_install:
  # Repo for Yarn
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq yarn; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull electronuserland/electron-builder:wine ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install --ignore-dependencies yarn ; fi
  - curl -O https://raw.githubusercontent.com/rockymadden/transfer-cli/master/src/transfer && chmod +x transfer
  
install:
  - yarn install

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dockerdist:linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dockerdist:win; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then yarn dist:mac; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./transfer upload dist/jupyterlab_app-*.AppImage; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./transfer upload dist/jupyterlab_app-*.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./transfer upload dist/jupyterlab_app-*.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./transfer upload dist/jupyterlab_app-*.rpm; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./transfer upload dist/JupyterLab\ App\ +([0-9]).+([0-9]).+([0-9]).exe; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./transfer upload dist/JupyterLab\ App\ Setup\ +([0-9]).+([0-9]).+([0-9]).exe; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./transfer upload dist/JupyterLab\ App-*.dmg; fi

+([0-9])
  

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
    
notifications:
  email: false
